global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: your@gmail.com
    from: your@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: your@gmail.com
    auth_identity: your@gmail.com
    auth_password: your_passwd_from_application
    send_resolved: true
