Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |node|
    node.memory = "1024"
    node.cpus = 1 
  end	
  config.vm.box = "generic/ubuntu2004"
  (1..3).each do |i|
    config.vm.define "ansible_vm#{i}" do |node|
     node.vm.box = "generic/ubuntu2004"
     node.vm.network :private_network, ip: "192.168.56.#{200+i}"
     node.vm.define vm_name = "ansible_#{i}"
     node.vm.provider "virtualbox" do |vb|
       vb.name = "ansible_#{i}"
       vb.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
       vb.customize ["modifyvm", :id, "--memory", 1024]
       vb.customize ["modifyvm", :id, "--cpus", 1]
     end
    end
  end
end
