---
- hosts: webserver
  remote_user: cch
  become: true    
  become_method: sudo

  tasks:
    - name: create file
      file: name=./{{ item }} state=touch
      with_items:
        - file1
        - file2
        - file3
    - name: install packages
      apt: name={{ item }}
      with_items:
        - sl
        - htop
