version: '3.6'
services:
  cerebro:
    image: yannart/cerebro
    container_name: cerebro
    ports:
      - "9000:9000"
    restart: unless-stopped
    networks:
      - efk
  dejavu:
    image: appbaseio/dejavu:latest
    container_name: dejavu
    ports:
      - "1358:1358"
    restart: unless-stopped
    networks:
      - efk
networks:
  efk:
    external:
      name: efk
